language: ruby
rvm:
  - 2.4
cache: bundle
sudo: required

branches:
 only:
 - master
 - draft

before_install:
  - echo '-----------------> setup timezone'
  - echo 'Australia/Melbourne' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
  - sudo ntpdate ntp.ubuntu.com
  - date

install:
  - bundle install --jobs=4
  - bundle exec jekyll build

jobs:
  include:
    - stage: deploy
      if: branch = master
      script:
        - echo "-----------------> algolia"
        - bundle exec jekyll algolia
    - stage: test
      if: branch = draft
      script:
        - echo "DONE"

before_deploy: 
  - echo '-----------------> prepare to deploy'
  - rm -R public
  - mv _site public

deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "OurWiTQ64D1UU/4shIqnVq6et1WmgFFetnqqn+n03hZ6cAUiWKad0l4DLfLTghO6q8SGNqgy/rQXSQBeKNnFM4RuVVdUtqpU3rs6TkMbLPuak9sYnAfsrm2IKji4WXW5N151rlDoPQxUR7bzJVWZJGMsnPjGBu+19Pp4sFPjX1Zm7g7vMMNAPXT8EbJoR3+8dQXEXtYwZgOyAsc2Yssezyic8l5YMXSqqVU1maJS57+A+wsP3iOwxv3usYiExZq2y7ppFJarFOgfT9ED8xhe3+xBnDEAZ5dVOMo/gNKOXEgDllYG7S7QbsChjHZswqoSbLTn1eUUVjkd7vqbpDt79+n7vYIQI1hPMPlZ7541arhlNN2ELOMCtwsNWKgarRYErpSPzLg8cFKKGOpeSaA4hsIbVup9zm93l49o/8HdDFWAIU7bIXX0pepZRwbiedWrs9DnmgEgNgmJB0vIW9cAZMkvFOipddHBCuSc96GyjOIwTvafWgfif6vLcVSqU1uZhgdrJ25FQ0M7SlmHCzLASFmxjAN7qcK2+wJioq0UWo6D7pfk9l6LNrK9xLM7OowGROD1DNtfOR121qxr1I8ZM3ts7S99hi4bUN6zgfqumTCgmNNCzy+d2dGnWHszKepl3rf4sGUBLlkcCooG/VVygIqVbZ5Gl2TudIxgCaK05so="
  project: "liduan-net"
  on:
    branch: master

after_deploy: 
  - echo '-----------------> finish deploy'

notifications:
  email:
    recipients:
      - inputx@gmail.com
    on_success: change # default: change
    on_failure: always # default: always
