language: ruby
rvm:
  - 2.4

sudo: required

branches:
 only:
 - master
 - draft
 - features/firebase-hosting

install:
  - bundle install --jobs=4
  - bundle exec jekyll build

jobs:
  include:
    - stage: deploy
      if: branch = features/firebase-hosting
      script:
        - echo "-----------------> algolia"
        - bundle exec jekyll algolia
        - echo "-----------------> prepare for firebase hosting"
        - mv _site public
    - stage: test
      if: branch = draft
      script:
        - echo "DONE"


deploy:
  provider: firebase
  token:
    secure: "YOUR ENCRYPTED token"
  project: "liduan-net"
  on:
    branch: features/firebase-hosting


notifications:
  email:
    recipients:
      - inputx@gmail.com
    on_success: change # default: change
    on_failure: always # default: always
