sudo: required

services:
  - docker

before_install:
  - docker pull topdevbox/static-website-toolbox
  - docker run -it --name="toolbox" topdevbox/static-website-toolbox /bin/bash -c "git clone $REPO; cd $REPODIR;bundle install;jekyll build;"


notifications:
  email:
    recipients:
      - $EMAIL1
    on_success: change # default: change
    on_failure: always # default: always