# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Liduan Worklog
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write down what's on your mind
#baseurl: "/worklog" # the subpath of your site, e.g. /blog
#url: "https://inputx.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/"
url: "https://liduan.net"
twitter_username: inputx
github_username:  inputx

paginate: 10

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-mermaid
  - jekyll-paginate


#paginate_path: "/worklog/page:num/"
paginate_path: "/page:num/"


# hyde ##############################
# Dependencies
# markdown:         redcarpet
# highlighter:      pygments

# Permalinks
# permalink:        pretty
# relative_permalinks: true

# Setup
tagline:          'Tech'

author:
  name:           'inputx'
  url:            https://github.com/inputx

# Custom vars
version:          2.1.0

# hyde ##############################


algolia:
  application_id: 'JW7LLYK6XP'


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
