name: Build and deploy static site

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby 2.4
      uses: actions/setup-ruby@v1
      with:
        version: 2.4.x

    - name: install
      run: |
        bundle install --jobs=4
        bundle exec jekyll build --future