name: Build and deploy static site

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby 2.4
      uses: actions/setup-ruby@v1
      with:
        version: 2.4.x

    - name: before install (tools)
      run: |
        sudo apt-get install npm -y
        gem install bundler
        sudo npm install -g firebase-tools
    - name: install
      run: bundle install --jobs=4
    - name: building
      run: bundle exec jekyll build --future
    - name: after building - update algolia
      run: bundle exec jekyll algolia
      env:
        ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}

    - name: before deploy - opt directory
      run: |
        rm -R public
        mv _site public
        firebase deploy --token "$FIREBASE_TOKEN"
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}